import type { Deposit } from "./mock-data";

/** Minimal offline seed so the pitch demo works when the Python API is not running. */
export const OFFLINE_FALLBACK_DEPOSITS: Deposit[] = [
  {
    id: "risk-001",
    sender: "Swf8EfykLf9gTfioYikpCbLzzxJx959GRdL2ahe3c89C",
    amount: "12.50",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    riskScore: 100,
    verdict: "BLOCKED",
    directHit: true,
    factors: [
      { type: "match", text: "Sender address is a direct match to OFAC: Lazarus Group on the sanctions list." },
      { type: "policy", text: "Direct OFAC matches are auto-rejected at the off-ramp." },
    ],
    auditNote: "Direct sanctions hit — auto-rejected (offline demo seed).",
    signals: {
      hopsToSanctioned: 0,
      mixerInPath: false,
      exposedVolume: "12.5000 SOL",
      hopsTraced: 4,
      sanctionLabel: "OFAC: Lazarus Group",
    },
  },
  {
    id: "risk-002",
    sender: "tsFTUsLneHr3KFsZuiGiqA6Hk7qemRRqhTpnr9dJ3HX5",
    amount: "1.60",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 21).toISOString(),
    riskScore: 84,
    verdict: "REVIEW",
    directHit: false,
    factors: [
      { type: "hops", text: "Funds reached the sender 2 hops downstream of a sanctioned source." },
      { type: "mixer", text: "Path routes through gone.wtf mixer, used to obscure fund origin." },
      { type: "obfuscation", text: "Obfuscation detected: mixer interaction — deposit pending review." },
    ],
    auditNote: "Mixer path flagged for analyst review (offline demo seed).",
    signals: {
      hopsToSanctioned: 2,
      mixerInPath: true,
      mixerLabel: "gone.wtf mixer",
      exposedVolume: "1.6000 SOL",
      hopsTraced: 4,
      sanctionLabel: "OFAC: Lazarus Group",
    },
    assigneeId: "mr",
  },
  {
    id: "risk-003",
    sender: "zje4ubgNmqudTgbedY4EnbRDKdwuL9odEGjzFRfai5HY",
    amount: "3.70",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    riskScore: 86,
    verdict: "REVIEW",
    directHit: false,
    factors: [
      { type: "hops", text: "Funds reached the sender 2 hops downstream of OFAC: Garantex." },
      { type: "mixer", text: "Path routes through Sinbad mixer, used to obscure fund origin." },
    ],
    auditNote: "Sinbad mixer exposure — pending review (offline demo seed).",
    signals: {
      hopsToSanctioned: 2,
      mixerInPath: true,
      mixerLabel: "Sinbad mixer",
      exposedVolume: "3.7000 SOL",
      hopsTraced: 4,
      sanctionLabel: "OFAC: Garantex",
    },
    assigneeId: "mr",
  },
  {
    id: "risk-004",
    sender: "JfQAEVNfi1rdhFtNwH2zWaxCmh68AdNmjddv76SHDF2t",
    amount: "5.50",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 43).toISOString(),
    riskScore: 72,
    verdict: "REVIEW",
    directHit: false,
    factors: [
      { type: "hops", text: "Funds reached the sender 3 hops downstream of OFAC: Garantex." },
    ],
    auditNote: "Plain peel chain taint — pending review (offline demo seed).",
    signals: {
      hopsToSanctioned: 3,
      mixerInPath: false,
      exposedVolume: "5.5000 SOL",
      hopsTraced: 4,
      sanctionLabel: "OFAC: Garantex",
    },
    assigneeId: "mr",
  },
  {
    id: "risk-005",
    sender: "7xKmPqR3nWv8YtL2jHf5sDc9bAe4uGi6oNp1rTq8vXzM",
    amount: "4.50",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 54).toISOString(),
    riskScore: 74,
    verdict: "REVIEW",
    directHit: false,
    factors: [
      {
        type: "velocity",
        text: "52 micro-transactions in 1 hour(s) (avg 0.1100 SOL) — suspected peel chain / structuring.",
      },
    ],
    auditNote: "Velocity structuring alert (offline demo seed).",
    signals: {
      hopsToSanctioned: 99,
      mixerInPath: false,
      exposedVolume: "0.0000 SOL",
      hopsTraced: 4,
      txVelocity: "52 tx / 1h",
    },
    behavioralAlert: {
      type: "velocity_structuring",
      tx_count: 52,
      window_hours: 1,
      avg_amount_sol: 0.11,
      pattern: "peel_chain",
    },
    assigneeId: "mr",
  },
  {
    id: "risk-006",
    sender: "QXTTDhVfJ24NaZi3DMLMzRRyzd3nRfQfx4JJQLkNihqE",
    amount: "0.85",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    riskScore: 85,
    verdict: "REVIEW",
    directHit: false,
    factors: [{ type: "hops", text: "Funds reached the sender 1 hop downstream of OFAC: Lazarus Group." }],
    auditNote: "One-hop taint — awaiting documents (offline demo seed).",
    signals: {
      hopsToSanctioned: 1,
      mixerInPath: false,
      exposedVolume: "0.8500 SOL",
      hopsTraced: 4,
      sanctionLabel: "OFAC: Lazarus Group",
    },
    assigneeId: "mr",
  },
  {
    id: "risk-007",
    sender: "xE9PkWjkdohYysYkAZVw1ji6eTTuJTDcF6nGgeAjBGEx",
    amount: "2.10",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 76).toISOString(),
    riskScore: 76,
    verdict: "REVIEW",
    directHit: false,
    factors: [
      { type: "identity", text: "Behaviorally linked to a tainted wallet with 76.0% confidence." },
    ],
    auditNote: "Identity link — awaiting documents (offline demo seed).",
    signals: {
      hopsToSanctioned: 2,
      mixerInPath: false,
      exposedVolume: "2.1000 SOL",
      hopsTraced: 4,
    },
    assigneeId: "mr",
  },
  {
    id: "risk-008",
    sender: "DpQ6wAz9eGRFQB4SCMjtd2rHDsudi98daGK5C8w6myzg",
    amount: "0.0009",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 87).toISOString(),
    riskScore: 14,
    verdict: "CLEARED",
    directHit: false,
    factors: [
      { type: "quarantine", text: "Received 0.0009 SOL of unsolicited dust from sanctioned mixer." },
      { type: "policy", text: "Quarantined instead of flagging the wallet; protects against dusting." },
    ],
    auditNote: "Dust quarantine cleared (offline demo seed).",
    signals: {
      hopsToSanctioned: 99,
      mixerInPath: false,
      exposedVolume: "0.0009 SOL",
      hopsTraced: 4,
    },
  },
  {
    id: "risk-009",
    sender: "G1yGSUm2pEksdQHpeXTcfQytcmnVmfRBU86itkaZygui",
    amount: "3.40",
    token: "SOL",
    receivedAt: new Date(Date.now() - 1000 * 60 * 98).toISOString(),
    riskScore: 6,
    verdict: "CLEARED",
    directHit: false,
    factors: [{ type: "clean", text: "No blocked source found within the 4-hop reverse search." }],
    auditNote: "Clean wallet — auto-accepted (offline demo seed).",
    signals: {
      hopsToSanctioned: 99,
      mixerInPath: false,
      exposedVolume: "0.0000 SOL",
      hopsTraced: 4,
    },
  },
];
